welcome.message: Hello, Spring Boot


spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
#Redis 配置
    redis:
    #Redis数据库索引
      database: 0
      host: 192.168.79.128
      port: 6379
      password: 123456
      pool:
      jedis:
        pool:
        #连接池最大连接数 使用负值表示没有限制
          max-active: 8
        #连接池最大阻塞等待时间(使用负值表示没有限制)
          max-wait: -1
        #连接池中的最大空闲连接
          max-idle: 8
        #连接池中最小空闲连接
          min-idle: 0
      #连接超时时间（毫秒）
      timeout: 0

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hjc.demo.entity

logging:
  level:
    com.hjc.demo : debug
  path: /usr/logs

#jwt 配置
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: restapiuser
  expiresSecond: 172800