package com.hjc.demo.mapper;

import com.hjc.demo.entity.SchedulerCronConfig;
import com.hjc.demo.entity.SchedulerCronConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SchedulerCronConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    long countByExample(SchedulerCronConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int deleteByExample(SchedulerCronConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int insert(SchedulerCronConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int insertSelective(SchedulerCronConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    List<SchedulerCronConfig> selectByExample(SchedulerCronConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    SchedulerCronConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchedulerCronConfig record, @Param("example") SchedulerCronConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchedulerCronConfig record, @Param("example") SchedulerCronConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SchedulerCronConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scheduler_cron_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SchedulerCronConfig record);

    /**
     * 根据id查询返回SchedulerCronConfig
     * @param id
     * @return
     */
    SchedulerCronConfig getSchedulerCronConfigById(@Param("id") long id);
}